/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GetToken.java
 *
 * Created on Apr 30, 2014, 3:26:12 AM
 */
package ParkingSystem;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author PJ
 */
public class GetToken extends javax.swing.JFrame {
    Statement st;
    ResultSet rs;
    String customerName,vehicleNumber,currentDate,currentTime,vehicleType,floorNumber,slotNumber;
    /** Creates new form GetToken */
    public GetToken() 
    {

    }
    String getToken()
    {
        String tokenNumber="";
        Statement st=DBConnector.getStatement();
        try 
        {
            ResultSet rs=st.executeQuery("select tokenID from tokengenerator where customername='"+customerName+"' AND vehicleNumber='"+vehicleNumber+"' AND currentDate='"+currentDate+"' AND currentTime='"+currentTime+"'");
            while(rs.next())
            {
                tokenNumber=rs.getString(1);
            }
        } 
        catch (SQLException e) 
        {
            System.out.println(e);
        }
        return tokenNumber;
    }
    public GetToken(String customerName, String vehicleNumber, String currentDate, String currentTime, String vehicleType) 
    {
        this.customerName = customerName;
        this.vehicleNumber = vehicleNumber;
        this.currentDate = currentDate;
        this.currentTime = currentTime;
        this.vehicleType = vehicleType;
        initComponents();
        
        try
        {
            st=DBConnector.getStatement();
            
            String query1="select floorNumber, slotNumber from status where status='free' and vehicletype='"+vehicleType+"'";
            rs=st.executeQuery(query1);
            if(rs.next())
            {
                floorNumber=rs.getString(1);
                slotNumber=rs.getString(2);
                
                String query2="INSERT INTO tokengenerator(CustomerName,vehicleNumber,CurrentDate,currentTime,vehicleType,floorNumber,slotNumber,currenttimemilis) VALUES ('"+customerName+"','"+vehicleNumber+"','"+currentDate+"','"+currentTime+"','"+vehicleType+"','"+floorNumber+"','"+slotNumber+"','"+System.currentTimeMillis()+"')";
                int i=st.executeUpdate(query2);
                if(i>0)
                {
                    String query3="Update parking.status set status='busy' where slotnumber='"+slotNumber+"'";
                    System.out.println(query3);
                    int j=st.executeUpdate(query3);
                    if(j>0)
                    {
                        System.out.println("Updated");
                    }
                    tokenNumber.setText("Token Number: "+getToken());
                    uName.setText(customerName);
                    vNumber.setText(vehicleNumber);
                    vType.setText(vehicleType);
                    cDate.setText(currentDate);
                    cTime.setText(currentTime);
                    fNum.setText(floorNumber);
                    sNum.setText(slotNumber);
                }
                else
                {
                    System.out.println("Record Not Inserted");
                }
            }
            else
            {
                new NoFreeSlot().setVisible(true);
                this.setVisible(false);
            }
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tokenNumber = new javax.swing.JLabel();
        uName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        vNumber = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vType = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cDate = new javax.swing.JLabel();
        cTime = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fNum = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sNum = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Customer Name:");

        tokenNumber.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tokenNumber.setForeground(new java.awt.Color(255, 0, 0));
        tokenNumber.setText("Token Number: ");

        uName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        uName.setText("Customer Name:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Vehicle Number:");

        vNumber.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        vNumber.setText("Customer Name:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Vehicle Type:");

        vType.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        vType.setText("Vehical Number");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Date:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Time:");

        cDate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cDate.setText("Date:");

        cTime.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cTime.setText("Date:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Floor Number:");

        fNum.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        fNum.setText("Slot Number:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Slot Number:");

        sNum.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sNum.setText("Slot Number:");

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(tokenNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sNum)
                    .addComponent(fNum)
                    .addComponent(uName)
                    .addComponent(vNumber)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tokenNumber)
                            .addComponent(jButton1))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(uName))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(vType)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(vNumber)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cDate)
                        .addGap(18, 18, 18)
                        .addComponent(cTime)
                        .addGap(18, 18, 18)
                        .addComponent(fNum)
                        .addGap(18, 18, 18)
                        .addComponent(sNum)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GetToken().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cDate;
    private javax.swing.JLabel cTime;
    private javax.swing.JLabel fNum;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel sNum;
    private javax.swing.JLabel tokenNumber;
    private javax.swing.JLabel uName;
    private javax.swing.JLabel vNumber;
    private javax.swing.JLabel vType;
    // End of variables declaration//GEN-END:variables
}
